# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive
# Sidebar
sidebar: right
widgets:
- tagcloud
- archive
- recent_posts
# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-120599346-1
#gauges_analytics:
favicon: /favicon.png
twitter: daishi0120
google_plus:
fb_admins:
fb_app_id:
